"""Pydantic schemas and JSON parsing utilities for local agent reasoning outputs.

Defines schemas for Planning, Error Investigation, Surgical Patching,
and Report & Voice Briefing synthesis.
"""

import json
import logging
import re
from typing import Any, Dict, List, Optional, Type, TypeVar
from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger("outofoffice.agent.schemas")

T = TypeVar("T", bound=BaseModel)


# ----------------------------------------------------------------------
# Planning Schemas
# ----------------------------------------------------------------------

class PlanItem(BaseModel):
    """An individual execution step in the agent's autonomous plan."""
    step_index: int = Field(..., description="1-indexed step order")
    step_name: str = Field(..., description="Short title of the step, e.g., 'Inspect TypeScript AST'")
    tool_name: str = Field(..., description="Name of tool to execute: repo_discovery, ast_parser, test_runner, linter_runner, search_engine, patcher, reporter")
    tool_args: Dict[str, Any] = Field(default_factory=dict, description="Arguments to pass to the tool")
    rationale: str = Field(default="", description="Why this step is necessary")


class PlanOutput(BaseModel):
    """Structured plan generated by Gemma from the user's prompt and repository metadata."""
    summary: str = Field(..., description="High-level plan summary")
    estimated_minutes: int = Field(default=5, description="Estimated compute time in minutes")
    steps: List[PlanItem] = Field(..., description="Sequential list of planned steps")

    @field_validator("steps")
    @classmethod
    def validate_steps_not_empty(cls, v: List[PlanItem]) -> List[PlanItem]:
        if not v:
            raise ValueError("Plan must contain at least one step.")
        return v


# ----------------------------------------------------------------------
# Root-Cause Investigation Schemas
# ----------------------------------------------------------------------

class InvestigationOutput(BaseModel):
    """Result of an autonomous error/dead-code investigation."""
    issue_title: str = Field(..., description="Concise title of the issue")
    severity: str = Field(default="MEDIUM", description="HIGH, MEDIUM, LOW, or INFO")
    category: str = Field(default="DEAD_CODE", description="DEAD_CODE, TEST_FAILURE, LINT_ERROR, TYPE_ERROR, UNUSED_DEPENDENCY")
    file_path: str = Field(..., description="Primary file path where the issue resides")
    line_number: Optional[int] = Field(default=None, description="Line number if identifiable")
    root_cause: str = Field(..., description="Detailed explanation of what is wrong")
    evidence: str = Field(..., description="Deterministic proof (e.g. 0 callers in codebase, test stack trace)")
    confidence: str = Field(default="HIGH", description="HIGH, MEDIUM, or LOW")
    is_safe_to_fix: bool = Field(default=False, description="Whether this issue can be safely patched without human intervention")
    fix_approach: Optional[str] = Field(default=None, description="Proposed method to resolve the issue safely")


# ----------------------------------------------------------------------
# Code Modification & Patching Schemas
# ----------------------------------------------------------------------

class PatchOutput(BaseModel):
    """Surgical file patch proposed by the agent."""
    file_path: str = Field(..., description="Relative file path to modify")
    original_code_block: str = Field(..., description="Exact original code block to be replaced (must match file contents)")
    replacement_code_block: str = Field(..., description="New code to replace the original code block with")
    explanation: str = Field(..., description="Why this change was made and why it is safe")
    confidence: str = Field(default="HIGH", description="Confidence level in this fix")


# ----------------------------------------------------------------------
# Report & Voice Briefing Schemas
# ----------------------------------------------------------------------

class ReportOutput(BaseModel):
    """Final report and voice briefing synthesis output."""
    health_score: int = Field(..., ge=0, le=100, description="Repository health score from 0 to 100")
    summary: str = Field(..., description="Executive summary of the completed autonomous run")
    files_analyzed_count: int = Field(default=0, description="Total number of files inspected")
    issues_found_count: int = Field(default=0, description="Total number of findings identified")
    safe_fixes_applied_count: int = Field(default=0, description="Total number of safe fixes applied and validated")
    test_summary: str = Field(default="", description="Summary of test pass/fail results, e.g., '47/47 tests passed'")
    key_findings: List[str] = Field(default_factory=list, description="Bullet points of key findings")
    voice_brief_script: str = Field(
        ...,
        description="Warm, natural-language 30-45 second script for ElevenLabs voice narration (e.g., 'Welcome back! While you were out touching grass for 24 minutes...')"
    )


# ----------------------------------------------------------------------
# Robust JSON Parsing & Extraction Helpers
# ----------------------------------------------------------------------

def extract_json_block(text: str) -> str:
    """Extracts raw JSON content from markdown code fences or surrounding text."""
    clean = text.strip()

    # Match ```json ... ``` or ``` ... ```
    json_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", clean, re.IGNORECASE)
    if json_match:
        return json_match.group(1).strip()

    # Find first '{' or '[' and last '}' or ']'
    first_brace = clean.find("{")
    first_bracket = clean.find("[")

    start_idx = -1
    if first_brace != -1 and first_bracket != -1:
        start_idx = min(first_brace, first_bracket)
    elif first_brace != -1:
        start_idx = first_brace
    elif first_bracket != -1:
        start_idx = first_bracket

    if start_idx != -1:
        last_brace = clean.rfind("}")
        last_bracket = clean.rfind("]")
        end_idx = max(last_brace, last_bracket)
        if end_idx != -1 and end_idx > start_idx:
            return clean[start_idx : end_idx + 1].strip()

    return clean


def repair_json_string(json_str: str) -> str:
    """Applies common heuristics to fix slightly malformed JSON from local LLMs."""
    repaired = json_str.strip()

    # Remove trailing commas before closing braces/brackets
    repaired = re.sub(r",\s*(\}|\])", r"\1", repaired)

    return repaired


def parse_and_validate_json(raw_text: str, schema_cls: Type[T]) -> T:
    """Extracts, repairs, and parses raw text into a validated Pydantic model."""
    extracted = extract_json_block(raw_text)
    repaired = repair_json_string(extracted)

    try:
        data = json.loads(repaired)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse JSON string: {e}\nRaw output:\n{raw_text}")
        raise ValueError(f"Could not parse valid JSON from model output: {e}")

    try:
        return schema_cls.model_validate(data)
    except Exception as e:
        logger.error(f"JSON data failed Pydantic validation for {schema_cls.__name__}: {e}")
        raise
